### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by viri77** [viri77/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by kwakkwel** [comment]
<h1>Ron Weasley</h1>
<div class="job">
<p >co-owner Weasleys' Wizard Wheezes</p>
</div>

<ul class="contacts">
<li>
<a class="magic" href="
https://www.facebook.com/RonaldGingerWeasley/" target="_blank">
<img class='custome-image' src="
https://img.icons8.com/doodle/48/000000/facebook-new.png" width="30" height=
"30" alt='Telegram'/>
ronweasley
</a>
</li>
<li>
<a class="magic" href="
https://www.instagram.com/ronhermione_id/" target="_blank">
<img class='custom-img' src="
https://img.icons8.com/doodle/48/000000/instagram-new.png" width="30" height
="30" alt='Instagram'/>
ronhermione_id
</a>
</li>
<li>
<a class="magic" ***@***.***"
>
<img class='custom-img' src="
https://img.icons8.com/doodle/48/000000/apple-mail.png" width="30" height=
"30"
alt='Gmail'/>
***@***.***
</a>
</li>
</ul>
</div>

**Comment by viri77** [comment]
<h3>Personal Life</h3>


 2008
 Birth of our son Hugo Granger-Weasley

 2006
 Birth of our daughter Rose «Rosie» Granger-Weasley

 1999
 Married Hermione Granger

вс, 2 мая 2021 г. в 22:22, kwakkwel ***@***.***>:

**Comment by viri77** [comment]
<h3>Experience</h3>

 2000-now
 Co-owner Weasleys' Wizard Wheezes

 2017, august
 Obtained a Muggle driving licence

  2014
 Attended the  final of the 427th Quiddich World Cup

  2010
 Was featured(with Harry and Hermoine) on Chocolate Frog Cards. My finest
hour ;)

  1998-2000
 Worked as Auror at Ministry of Magic along with Harry Potter and Hermione
Granger

  1998
 Faught in the Battle of Hogwarts

  1997
 Participated in Battle of Hogwarts

  1996
 Won the Quiddich cup

 1996
 Won the  position of Keeper on the Gryffindor Quiddich team

  1992
 Was honoured with a Special Award for Services to the School(two hundred
House points for Gryffindor)

  1991
 Was sorted into Gryffindor House

  1991
 Began attending  Hogwarts School of Witchcraft and Wizardry

пн, 3 мая 2021 г. в 00:30, Ольга ***@***.***>:
