### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by viri77** [viri77/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by kwakkwel** [comment]
<h3>Personal Life</h3>


2008
Birth of our son Hugo Granger-Weasley

2006
Birth of our daughter Rose «Rosie» Granger-Weasley

1999
Married Hermione Granger

**Comment by kwakkwel** [comment]
<h3>Experience</h3>

2000-now
Co-owner Weasleys' Wizard Wheezes

2017, august
Obtained a Muggle driving license

2014
Attended the final of the 427th Quiddich World Cup

2010
Was featured(with Harry and Hermoine) on Chocolate Frog Cards. My finest
hour ;)

1998-2000
Worked as Auror at Ministry of Magic along with Harry Potter and Hermione
Granger

1998
Faught in the Battle of Hogwarts

1997
Participated in Battle of Hogwarts

1996
Won the Quiddich cup

1996
Won the position of Keeper on the Gryffindor Quiddich team

1992
Was honoured with a Special Award for Services to the School(two hundred
House points for Gryffindor)

1991
Was sorted into Gryffindor House

1991
Began attending Hogwarts School of Witchcraft and Wizardry

**Comment by viri77** [comment]
<h3>Things I love veru much</h3>
<p>FOOD!!! </p>
<div style="padding-top:39.600%;position:relative;"><iframe src="
https://gifer.com/embed/3Sfs" width="100%" height="100%"
style='position:absolute;top:0;left:0;' frameBorder="0"
allowFullScreen></iframe></div><p><a href="https://gifer.com">через
GIFER</a></p>
<p>friends Quiddich</p>
<h3>Things I hate</h3>
<p>Poverty  being "second-best" to work a lot</p>
<p>Spiders</p>
<iframe src="https://gifer.com/embed/4Wab" width=480 height=391.837
frameBorder="0" allowFullScreen></iframe><p><a href="https://gifer.com">через
GIFER</a></p>
<h3>Skills</h3>
<p>Wizard Chess Dueling Degence against DarkArts Charms Flying</p>
<h3>My Strength    <img src="
https://img.icons8.com/emoji/48/000000/flexed-biceps.png" width="30"
height="30"/></h3>
<p>Leadership Tactical Thinking Loyality Sence of humor</p>

<h3>My weaknesses</h3>
<p>incredible laziness, swearing</p>

пн, 3 мая 2021 г. в 00:36, kwakkwel ***@***.***>:
