### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by viri77** [viri77/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by kwakkwel** [comment]
<h3>Things I love veru much</h3>
<p>FOOD!!! </p>
<div style="padding-top:39.600%;position:relative;"><iframe src="
https://gifer.com/embed/3Sfs" width="100%" height="100%"
style='position:absolute;top:0;left:0;' frameBorder="0"
allowFullScreen></iframe></div><p><a href="https://gifer.com">через
GIFER</a></p>
<p>friends Quiddich</p>
<h3>Things I hate</h3>
<p>Poverty being "second-best" to work a lot</p>
<p>Spiders</p>
<iframe src="https://gifer.com/embed/4Wab" width=480 height=391.837
frameBorder="0" allowFullScreen></iframe><p><a href="https://gifer.com">через
GIFER</a></p>
<h3>Skills</h3>
<p>Wizard Chess Dueling Degence against DarkArts Charms Flying</p>
<h3>My Strength <img src="
https://img.icons8.com/emoji/48/000000/flexed-biceps.png" width="30"
height="30"/></h3>
<p>Leadership Tactical Thinking Loyality Sence of humor</p>

<h3>My weaknesses</h3>
<p>incredible laziness, swearing</p>
